# Generated by Django 3.1.5 on 2021-03-27 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Green_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', fernet_fields.fields.EncryptedTextField(max_length=1000)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('FB_link', models.CharField(max_length=200, null=True)),
                ('Twitter_link', models.CharField(max_length=200, null=True)),
                ('Insta_link', models.CharField(max_length=200, null=True)),
                ('Linkedin_link', models.CharField(max_length=200, null=True)),
                ('social_media', models.CharField(max_length=200, null='None')),
                ('social_media_link', models.CharField(max_length=200, null=True)),
                ('privacy_info', models.IntegerField(default=0)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('dp', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Green_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Green_Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Website', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('Address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('landmark', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('maplocation', models.TextField()),
                ('dp', models.TextField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('contact', models.CharField(max_length=200, null=True)),
                ('FB_link', models.CharField(max_length=200, null='None')),
                ('Twitter_link', models.CharField(max_length=200, null=True)),
                ('Insta_link', models.CharField(max_length=200, null=True)),
                ('Linkedin_link', models.CharField(max_length=200, null=True)),
                ('social_media', models.CharField(max_length=200, null='None')),
                ('social_media_link', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
                ('BusinessFrom', unixtimestampfield.fields.UnixTimeStampField(null=True)),
                ('publist', unixtimestampfield.fields.UnixTimeStampField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusinessOwner', to='FoGApp.green_owner')),
            ],
        ),
    ]
