# Generated by Django 3.0.5 on 2021-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoGApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='green_business',
            name='type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='green_owner',
            name='dp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
