# Generated by Django 3.0.5 on 2021-03-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoGApp', '0002_auto_20210327_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='green_business',
            name='dp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
